### ISSUE TITLE
Arrumar problema dos links da Twitch

### ISSUE THREAD

**Issue by L3onix** [L3onix/view-embed#6]
Os links da Twitch não estão funcionando corretamente.
Tem que verificar a [documentação](https://dev.twitch.tv/docs/embed/video-and-clips/), acho que o problema esta na URL gerada pelo middlewares/UrlFactory.js

**Comment by felipehfs** [comment]
Olá @L3onix como eu posso te ajudar?

**Comment by L3onix** [comment]
Pode sim!
