### ISSUE TITLE
Arrumar problema com links do YouTube

### ISSUE THREAD

**Issue by L3onix** [L3onix/view-embed#7]
Links do YouTube que contém o seguinte padrão **https://youtu.be/** ainda não funcionam. Deve ser adicionada essa identificação na função *verifuUrlAndReturnNewUrl* do arquivo middlewares/UrlFactory.js

**Comment by maryanamorato** [comment]
posso tentar?

**Comment by felipehfs** [comment]
Posso ajudá-lo nessa tarefa?
