### ISSUE TITLE
Arrumar texto de descrição do modal about

### ISSUE THREAD

**Issue by L3onix** [L3onix/view-embed#8]
Remover todo o conteúdo do modal about (manter apenas o titulo) e substituir pela descrição que está no README.md. Arquivo relacionado a isso está localizado em components/AboutModal.js

**Comment by L3onix** [comment]
É melhor também manter o botão com link do projeto no GitHub

**Comment by maryanamorato** [comment]
ei, posso ajudar nisso?

**Comment by felipehfs** [comment]
Eu gostaria de ajudar.
