### ISSUE TITLE
Estilizar modal about

### ISSUE THREAD

**Issue by L3onix** [L3onix/view-embed#9]
O modal about precisa de uma estilização que combine com o estilo do site. Aquivo de CSS do modal about está localizado em components/AboutModal.css.

**Comment by felipehfs** [comment]
Olá @L3onix  como posso te ajudar?

**Comment by L3onix** [comment]
Pode sim!

**Comment by felipehfs** [comment]
Você quer que altere as cores ou o que mais e mantenha o modal?

**Comment by L3onix** [comment]
Qualquer alteração tava valendo, só queria que não ficasse tão neutro como estava antes
